### ISSUE TITLE
How to handle hierarchical resources?

### ISSUE THREAD

**Issue by vyshane** [zfcampus/zf-apigility#10]
Let's say I've got a user resource where a user may have zero or more related addresses. An address cannot exist without a user entity. Let's say that I want to be able to query for a user's addresses by hitting the following URL:

/users/:id/addresses

What would be the best way to do this with Apigility?

**Comment by benwaine** [comment]
@EMCP - Probably a bit old now but i just managed this by adding the following to my module.config.php file. 

```php 
<?php 

    'zf-hal' => array(
        'metadata_map' => array(
            'ListItem' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'lists.rest.list-item',
                'route_identifier_name' => 'list_item_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
                'route_params' => [
                    // list_id is the id of the list this item belongs to
                    'list_id' => function($object) {
                    // I'm using doctrine so I know this object will be present    
                    return $object->getList()->getId();
                    }
                ]
            ),
        ),
    ),
```

**Comment by benwaine** [comment]
I can see a drawback in complex layered resource layouts and the use of doctrine here. 

The call to getList() (or getAnything() - were anything is the name of a parent or child property) executes a database call to get the data and deserialise it into an object. 

The two options I can see are: 

1 -  [A DQL fetch join](http://doctrine-orm.readthedocs.org/en/latest/reference/dql-doctrine-query-language.html#joins) to fetch back the sections of the object graph required to generate the URL. 

2 - Using a [new Doctrine feature](http://doctrine-orm.readthedocs.org/en/latest/reference/dql-doctrine-query-language.html#new-operator-syntax) to construct a DTO which is the object expected by ZF-Hal and the one which the metadata map expects.

**Comment by TomHAnderson** [comment]
@benwaine have you used zf-apigility-doctrine?  Is what you describe not already handled there?

**Comment by benwaine** [comment]
@TomHAnderson I gave it a try, but the lack of documentation and it's incomplete state make it very difficult to implement. It looks very promising, but lacks polish. Also, I think the current composer dependancy settings don't work. 

I read all of the doctrine / apigility content on your blog, stackoverflow and in these issue pages. It was really helpful in getting me a working solution! When I have more time I'd like to sit down and try harder with apigility doctrine, but the line of business waits for no man.

**Comment by mgoneau** [comment]
Hi,

If possible, i'd also like an example of "injecting the entity" part of it. 

Thanks

**Comment by NathanHaley** [comment]
Appreciate everyones input on this thread, especially @weierophinney. 

Struggling with this too. 

Will adding the dependency affect being able to use the UI? I'm worried about overriding the non-ui additions to make basic row level access work OR that having custom/additional code in a module managed by Apigility will break the ability to use the UI to continue to manage that service. 

Basically want role based user access/administration like a typical site with functionality or CMS, having user's create all kinds of things specific to them like project/todo lists and I want to have layers of access for admins. Is this not a good fit for oauth and/or RESTful api's?

Thanks
