### ISSUE TITLE
Unable to render template "zf/app/app"

### ISSUE THREAD

**Issue by chateaux** [zfcampus/zf-apigility#100]
Running Apigility 1.1.3,

Did  recent update and started getting the following error when accessing: www.example.com/apigility/ui#/

Fatal error: Uncaught exception 'Zend\View\Exception\RuntimeException' with message 'Zend\View\Renderer\PhpRenderer::render: Unable to render template "zf/app/app"; resolver could not resolve to a file' in /trunk/vendor/zendframework/zendframework/library/Zend/View/Renderer/PhpRenderer.php on line 498

Not 100% sure where to start bug testing.

Kindly advise,

**Comment by tiberioalunni** [comment]
try to update zend to 2.4

**Comment by chateaux** [comment]
Ahh - 

Thank you, that did the trick.
