### ISSUE TITLE
Unable to DELETE resource with empty body

### ISSUE THREAD

**Issue by snowwolf007cn** [zfcampus/zf-apigility#101]
Exception thrown:
[Tue Apr 21 14:48:36 2015] PHP Catchable fatal error:  Argument 1 passed to ZF\ContentNegotiation\ParameterDataContainer::setBodyParams() must be of the type array, null given, called in /home/snowwolf/PhpStormProject/ffan-service/vendor/zfcampus/zf-content-negotiation/src/ContentTypeListener.php on line 111 and defined in /home/snowwolf/PhpStormProject/ffan-service/vendor/zfcampus/zf-content-negotiation/src/ParameterDataContainer.php on line 132

**Comment by tiberioalunni** [comment]
same problem happens on POST

**Comment by TomHAnderson** [comment]
Are you calling delete with an identifier or are you calling deleteList by not specifying an identifer?
e.g. with identifer (delete)
DELETE /api/endpoint/identifier
e.g without identifier (deleteList)
DELETE /api/endpoint

**Comment by tiberioalunni** [comment]
I solved the problem by passing a dummy parameter to the post (even if the RPC service don't require and don't have any filed)

The problem seems to be related to empty request payload (request body) when POST or DELETE method are used.

**Comment by snowwolf007cn** [comment]
with identifier

**Comment by snowwolf007cn** [comment]
I have exactly the same problem with @tiberioalunni

**Comment by Wilt** [comment]
Related to: https://github.com/zfcampus/zf-apigility/issues/101#issuecomment-95488109

**Comment by Webvida** [comment]
Same problem here, got this while doing the "status tutorial" - not nice for a new user to encounter :(

**Comment by weierophinney** [comment]
This was fixed with zfcampus/zf-content-negotiation#35, which was released in v1.0.5 of that module. Updating that dependency will fix the issues.
