### ISSUE TITLE
RPC zf-content-validation for MULTY Action in same controller

### ISSUE THREAD

**Issue by developer-devPHP** [zfcampus/zf-apigility#102]
in **module.config.php** I have this
```PHP
 'zf-content-validation' => array(
        'myApi\\V1\\Rpc\\Auth\\Controller' => array(
            'input_filter' => 'iguanApi\\V1\\Rpc\\Auth\\Validator',
      )
```

but in **myApi\\V1\\Rpc\\Auth\\Controller** controller I have many actions for example **login**, **registration** etc
so have any method to set validation for **each** **ACTION** not just request method (post,get,put, etc)

something like this 

```PHP
 'zf-content-validation' => array(
        'myApi\\V1\\Rpc\\Auth\\Controller' => array(
            'input_filter' => 'myApi\\V1\\Rpc\\Auth\\Validator',
            'actions'=>array(
                 'login'=>array(
                         'POST'=> 'myApi\\V1\\Rpc\\Auth\\Validator\\login'
                 ),
                 'registration'=>array(
                        'POST'=> 'myApi\\V1\\Rpc\\Auth\\Validator\\reg'
                 ),
                 .....
            ),
      )
```

**Comment by developer-devPHP** [comment]
Can anybody reply? If it is impossible now, Can you create this functionality in the future release?

**Comment by weierophinney** [comment]
See zfcampus/zf-content-validation#44 for my response; we do not plan to support multi-action controllers in Apigility.
