### ISSUE TITLE
How to include a URL as a parameter in a GET request

### ISSUE THREAD

**Issue by chateaux** [zfcampus/zf-apigility#104]
I am trying to pass a URL as a parameter in a simple RPC service using GET.

The route match is: /api/register/access/code/:access_code/:route

And the call would be:

/api/register/access/code/c102dea422fa4bb6958d77a29d9873d2/http%3A%2F%2Fexample.com%2Fapi%2Fdirectory

Now it would seem that ApiGility interprets the slash parts of the URL: %2F as a 'slash" and thus the routing breaks.

How do I get around this?

Many thanks,

**Comment by automatix** [comment]
Apigility interprets nothing. It's routes, that handle the request URLs. You can handle this with a [`RegEx Route`](http://framework.zend.com/manual/current/en/modules/zend.mvc.routing.html#zend-mvc-router-http-regex).

**Comment by chateaux** [comment]
Solved this by url encoding and base64 encoding...
