### ISSUE TITLE
What is the best way to build read-only fields for Services?

### ISSUE THREAD

**Issue by ThatGuyFromFinland** [zfcampus/zf-apigility#111]
We are building Cloud Service based architecture for a start-up.

Our front-end needs to know about the status of our integrations, but the front-end(s) should not be allowed to modify the status fields; thus we need to be able to define read-only fields. What is the best implementation for this? How to build it in a reusable way?

One way to implement this, would be using HTTP PATCH, with such implementation, that certain fields would fail EVERY time, with error message "this field is read-only and you should update the entity with PATCH request"; however, PATCH is not "part of the most official standard" HTTP and has less support than PUT (even though it has a good support).

With PUT requests, we would have to unset the read-only field with custom DbConnectedResource, that uses DI parameter e.g.: 'read-only' => array(fieldName1, fieldName2). Then a custom Factory would initiate the Resource that extends the DbConnectedResource.

Which one you would prefer and is there third / fourth alternatives?

**Comment by ezimuel** [comment]
@ThatGuyFromFinland why don't expose the `status` field with a simple `GET /status` and remove it from the UPDATE operations?

**Comment by ThatGuyFromFinland** [comment]
We are using DbConnectedResource and we have built a SyncApi which Syncs entities to external services like AWS. The asynchronous integrations are the reason we have the status fields in the first place.

We also need the full entities for Front-End, because we use a declarative component based views; when we add/modify Apigility Services, the views will adjust automaticly without any code, they read our metadescrptions from Apigility documentation.

Having clean domain objects with clear states enables us to use design patterns properly, e.g. object hydration is very important for us and it can't be done with spaghetti code.

**Comment by ThatGuyFromFinland** [comment]
Or did I misunderstand you?

In the second solution idea it does behave like that: GET gives the full entity and when updating, the entity is removed.

**Comment by Wilt** [comment]
I don't understand your problem. If you make an `InputFilter` and ommit read only fields it should all be working without issues. Or do you want to "tell" the client explicitly which fields are read-only? If yes, why can you give a user-case (UI) example...

**Comment by ThatGuyFromFinland** [comment]
What kind of InputFilter would you be suggesting?

We have built a Dashboard to central repository of our data, which is synchronizing itself to other external services with Synchronization API, that uses the same database, but exposes different columns. We want to build everything as declarative as possible to avoid writing boiler plate code that has to be tested.

We need to be able to show read-only fields and status codes in the Dashboard without the end-user being able to touch them. This would help our customer service operations etc.

We ended up building a FeatureEvent to the TableGateway, which attaches itself to the PRE_INSERT and PRE_UPDATE events and unsets the field, which is set to be read-only. I believe another developer already tried out InputFilter approach but it didn't quite work for us.

Of course, if there is a more simple InputFilter way of implementing this, I would be happy to hear about it! :)

**Comment by weierophinney** [comment]
If you omit those fields from the input filter, they won't be passed to the database on update() or create(). As long as your entity objects still incorporate them, you'll still see the values when you fetch them.
