### ISSUE TITLE
Error when create one table  with '_'

### ISSUE THREAD

**Issue by enlacee** [zfcampus/zf-apigility#113]
hi,
I got an error when I use a table called : **test_anibal**
This error occurs when you create tables with : '_'

i need support for this issue 
please let me know if I'm making a mistake.
but I think q is errror of apigility

thanks for you input (colaboration)

imagenes : 
01 : http://i60.tinypic.com/14e6mhu.png
02 : http://i59.tinypic.com/2qkmi6h.jpg
03 : http://i61.tinypic.com/302mkd5.png

![01](http://i60.tinypic.com/14e6mhu.png)
![01](http://i59.tinypic.com/2qkmi6h.jpg)
![01](http://i61.tinypic.com/302mkd5.png)

**Comment by weierophinney** [comment]
Fixed with zfcampus/zf-apigility-admin-ui#59, and we'll release it within the next 7 days.
