### ISSUE TITLE
Unable to create upload field

### ISSUE THREAD

**Issue by Michal-sk** [zfcampus/zf-apigility#115]
I am trying to create a upload field, but input-filter returns the following error

```json
{"validation_messages":{"inputFilter":"Input factory expects the \"type\" to be a valid class; received \"1\""},"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unprocessable Entity","status":422,"detail":"Failed Validation"}
```

I give the field a name, description, and set the checkbox for file upload. Than the above error shows in google developer tools.

**Comment by Michal-sk** [comment]
After some debugging it seems the ```type``` field send from the angular form contains a incorrect value:

```
[{"required":true,"validators":[],"filters":[],"name":"file","description":"file","allow_empty":true,"continue_if_empty":true,"type":true}]
```

Thats the content being posted from the model window where we control the fields. Type field should be ```Zend\InputFilter\FileInput``` when looking at the html.

```
<input type="checkbox" ng-model="vm.field.type" value="Zend\InputFilter\FileInput" class="col-sm-2 control-label ng-valid ng-dirty">
```

**Comment by Michal-sk** [comment]
Ok looking at ```Zend\Form\Element\File``` i saw the ```type => file``` attribute and changed the html value of the checkbox to file, and now saving works.

**Comment by Socengel** [comment]
The same.

**Comment by Michal-sk** [comment]
Fixed https://github.com/zfcampus/zf-apigility-admin/issues/287
