### ISSUE TITLE
Why is this repo outdated?

### ISSUE THREAD

**Issue by dmelo** [zfcampus/zf-apigility#116]
Apigility is on version 1.1.1, while this repo still on version 1.0.3. There has been 4 releases since then.

I think packagist (composer) is linked to this repo, because the newest version from composer is also 1.0.3.

Is the official version of apigility on another repo (outside of github)?

**Comment by TomHAnderson** [comment]
Wy do all related repos need to have the same version?  Isn't the ability to develop repositories on their own the reason zendframework was split?

**Comment by dmelo** [comment]
I'm sorry. My mistake. I through the download https://apigility.org/download was for the zf-apigility, not the zf-apigility-skeleton.
