### ISSUE TITLE
Always getting forbidden using oauth2

### ISSUE THREAD

**Issue by fabiopaiva** [zfcampus/zf-apigility#117]
if i acccess using Postman GET:

     http://localhost:8888/oauth/resource
     Accept:application/json
     Content-Type: application/json
     Authorization: Bearer 46df6282adab91b109bb1342cb6d98e336ebce0e

response:

    {
        "success": true,
        "message": "You accessed my APIs!"
    }

but, if i try to access a simple RPC GET

     http://localhost:8888/rpc/test
     Accept:application/json
     Content-Type: application/json
     Authorization: Bearer 46df6282adab91b109bb1342cb6d98e336ebce0e

response:

    {
        "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
        "title": "Forbidden",
        "status": 403,
        "detail": "Forbidden"
    }

versions
zfcampus/zf-api-problem             1.0.2              ZF2 Module providing API-Problem assets and rendering
zfcampus/zf-apigility               1.0.3              Apigility module for ZF2
zfcampus/zf-apigility-admin         1.1.2              Apigility Admin module
zfcampus/zf-apigility-admin-ui      1.1.4              Apigility Admin UI module
zfcampus/zf-apigility-documentation 1.0.5              Apigility API documentation module
zfcampus/zf-apigility-provider      1.0.1              Apigility interfaces
zfcampus/zf-configuration           1.0.2              ZF2 Module providing REST resource for manipulating configuration
zfcampus/zf-console                 1.1.0              Library for creating and dispatching console commands
zfcampus/zf-content-negotiation     1.0.7              ZF2 Module providing content-negotiation features
zfcampus/zf-content-validation      1.1.0              ZF2 Module providing incoming content validation
zfcampus/zf-deploy                  1.0.4              Deployment tool for ZF2 application
zfcampus/zf-development-mode        2.0.5              ZF2 development mode module
zfcampus/zf-hal                     1.1.0              ZF2 Module providing Hypermedia Application Language assets and rendering
zfcampus/zf-mvc-auth                1.1.3              ZF2 Module providing Authentication and Authorization events and infrastructure
zfcampus/zf-oauth2                  1.1.2              ZF2 module for implementing an OAuth2 server
zfcampus/zf-rest                    1.1.0              ZF2 Module providing structure for RESTful resources
zfcampus/zf-rpc                     1.0.2              ZF2 Module for simplifying the creation of RPC services
zfcampus/zf-versioning              1.0.2              ZF2 Module providing listeners and route prototypes for implementing API versioning

**Comment by fabiopaiva** [comment]
i fix it adding this to config:

    'zf-mvc-auth' => array(
        'authentication' => array(
            'map' => array(
                'MyAPIName\\V1' => 'myOauth2AdapterName'
            )
        )
    )

**Comment by pappu687** [comment]
@fabiopaiva Thanks man. The day is saved.
