### ISSUE TITLE
PDO Exception wrapped with "7 Unknown Error" instead of "500 Internal Server Error"

### ISSUE THREAD

**Issue by permiakov** [zfcampus/zf-apigility#118]
Conditions:
- I have my database server stopped, so i am getting PDO Exception "Connect Error: SQLSTATE[08006] [7] could not connect to server"
- In my RPC(code connected) endpoint settings i accept only "application/json".

What is ok:
If i am not passing "Accept: application/json"  i am getting PDO Exception wrapped with "500 Internal Server Error" which is expected and html output of stack trace(without my own try/catching of course)

What is not ok:
With passing "Accept: application/json" apigility outputs "7 Unknown Error" with the same stack trace wrapped in JSON(expected). 

But "7 Unknown Error" is not a proper HTTP code - was looking in the code it takes PDO Exception integer code(7) and uses it instead of HTTP code when returns.

**Comment by weierophinney** [comment]
Verified. I'll try and get this fixed.

**Comment by permiakov** [comment]
Awesome, thank you
