### ISSUE TITLE
Unable to start application after updated from 1.1.2 to 1.3.0

### ISSUE THREAD

**Issue by snowwolf007cn** [zfcampus/zf-apigility#124]
Stack trace below:
    [Thu Jul 16 10:23:46 2015] PHP Fatal error:  Uncaught exception 'Zend\Stdlib\Exception\BadMethodCallException' with message 'The option "accept-whitelist" does not have a callable "setAccept-whitelist" ("setaccept-whitelist") setter method which must be defined' in /home/snowwolf/PhpStormProject/ffan-service/vendor/zendframework/zend-stdlib/src/AbstractOptions.php:110
    Stack trace:
    #0 /home/snowwolf/PhpStormProject/ffan-service/vendor/zendframework/zend-stdlib/src/AbstractOptions.php(62): Zend\Stdlib\AbstractOptions->__set('accept-whitelis...', Array)
    #1 /home/snowwolf/PhpStormProject/ffan-service/vendor/zendframework/zend-stdlib/src/AbstractOptions.php(32): Zend\Stdlib\AbstractOptions->setFromArray(Array)
    #2 /home/snowwolf/PhpStormProject/ffan-service/vendor/zfcampus/zf-content-negotiation/src/Factory/ContentNegotiationOptionsFactory.php(31): Zend\Stdlib\AbstractOptions->__construct(Array)
    #3 [internal function]: ZF\ContentNegotiation\Factory\ContentNegotiationOptionsFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'zfcontentnegoti...' in /home/snowwolf/PhpStormProject/ffan-service/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 946

**Comment by weierophinney** [comment]
You have a bad key in your configuration; replace `accept-whitelist` with `accept_whitelist` (I.e. use an underscore instead of a dash). (Previously, this service ignored invalid keys.)

**Comment by vik-singh** [comment]
@snowwolf007cn - Just submitted pull request to zf-apigility-doctrine module that had this bad config - https://github.com/zfcampus/zf-apigility-doctrine/pull/212

**Comment by snowwolf007cn** [comment]
@vik-singh thanks, I think that's what cause the problem. I've disable zf-apigility-doctrine temporarily and fix the problem.

**Comment by weierophinney** [comment]
I'm going to do a patch to zf-content-negotiation that will fix this. `accept-whitelist` is indeed incorrect, and is actually *ignored* currently, which means that zf-apigility-doctrine is incorrect. However, the patch I'm creating will munge that key so it works correctly.

**Comment by weierophinney** [comment]
I've opened a pull request here: zfcampus/zf-content-negotiation#48

Once merged, I'll also backport it to the 1.2 series to ensure PHP 5.3 and 5.4 users do not have issues.

**Comment by weierophinney** [comment]
Fixed with zfcampus/zf-content-negotiation#48.
