### ISSUE TITLE
Issues with authentication process

### ISSUE THREAD

**Issue by nuxwin** [zfcampus/zf-apigility#126]
See https://github.com/zfcampus/zf-apigility-skeleton/issues/104

**Comment by weierophinney** [comment]
Issue is in zf-mvc-auth; closing, and will open a new issue there.

**Comment by nuxwin** [comment]
@weierophinney

There is already a link ;)

https://github.com/zfcampus/zf-mvc-auth/issues/92

Sorry for all those back-refs.. I was not sure about the right place ;)
