### ISSUE TITLE
Autodiscovering tables fails on Oracle

### ISSUE THREAD

**Issue by mpalourdio** [zfcampus/zf-apigility#132]
Hello,

I am unable to create a DB connected service on Oracle 11. (Oci8 driver) The error returned when selecting the db adapter is ``ORA 01745 (invalid host/bind variable name)``.

A simple oci_connect() test works perfectly with the same instance/schema.

**Comment by vixriihi** [comment]
This is due to a bug in zend-db. There is already a PR to fix this (https://github.com/zendframework/zend-db/pull/34) so hopefully this will soon work with oracle also.

**Comment by mpalourdio** [comment]
Thanks for feedback, I will give your patch a try, hopefully, tomorrow.

**Comment by mpalourdio** [comment]
I have just tested your fix, and now the UI can list the tables, thanks !

But clicking the 'create service' after having selected a table doesn't do anything. The modal window doesn't close and the service isn't created.

The JS error triggered is ``Error: e.rest is undefined``. Looks more like an JS problem now !

**Comment by mpalourdio** [comment]
The .js bug is already fixed in master ! I can confirm that your fix works like a charm for the moment !
