### ISSUE TITLE
SSO - Expiry time

### ISSUE THREAD

**Issue by chateaux** [zfcampus/zf-apigility#138]
Hi - 

I am using ApiGility for SSO login on trusted apps and I am wondering if there is a way to increase the SSO expiry time of a given token from 3600 to 24 hours or longer?

Thanks,

**Comment by akrabat** [comment]
Ideally, your clients should use the refresh token to get a new access token. However you can change the token expiry length using this top-level configuration setting:

```php
    'zf-oauth2' => [
        'access_lifetime' => 7200,
    ],
```
