### ISSUE TITLE
Making a DB connected REST service gives Error: e.rest is undefined

### ISSUE THREAD

**Issue by migmolrod** [zfcampus/zf-apigility#140]
I have a Database adapter (both Mysqli and PDO_Mysql drivers give same error).
When I try to create a DB connected REST service, I can choose the adapter, Apigility correctly autodiscovers all tables.
But when I select one or more and click "Create service", JS console throws that *"Error: e.rest is undefined"*.

I've tried several different tables (with and without foreign keys), single tables and several in batch, etc. to no avail.

Have I missed a step? I couldn't find a good  article about a generic DB connected configuration in the official documentation.

**Comment by migmolrod** [comment]
Sorry, wrong repo. This should go to the zf-apigility-skeleton. And there is already an issue like this.
Closing this. Sorry again.

**Comment by tushariscoolster** [comment]
@migmolrod  https://github.com/tushariscoolster/apigility-db-connected-fix
