### ISSUE TITLE
entity_query_whitelist

### ISSUE THREAD

**Issue by GabrielDelepine** [zfcampus/zf-apigility#150]
Can we imagine have an `entity_query_whitelist` option, on the model of `collection_query_whitelist`?

Doc : https://apigility.org/documentation/modules/zf-rest

**Comment by SilverioMiranda** [comment]
If you want to return Entity you must provide ID only. For other filtering operations the return must be a collection
Like in sql:
Select * FROM table WHERE ID = 1
Select * FROM table WHERE ID = 1 AND OtherField > 1

The first query you expect return 0-1 row, and the second you can expect 0-n

There is no reason to make entity_query_whitelist

**Comment by SlashBin** [comment]
What if you want to optionally include more or less `_embedded` collections, or change the `depth` by query param? I could see a couple reasons why you might want to have a `entity_query_whitelist`

**Comment by GabrielDelepine** [comment]
Thanks @SlashBin for your response
I opened this issue a long time ago and I can't even remember what was my use case. I am not using apigility anymore, it's not part of the stack of my new company.
Thanks anyway
