### ISSUE TITLE
File upload discrepancy: POST vs PATCH

### ISSUE THREAD

**Issue by sariabod** [zfcampus/zf-apigility#185]
There is a slight difference in POST vs PATCH that is causing errors. Using POST everything works fine, switching to a PATCH causes RenameUpload to fail. I have put multipart/form-data into the whitelist and have also marked the field as "file upload". Here is a link to a gist that shows the data and the headers: **https://gist.github.com/sariabod/7e428ee893987332ddac93f67a02cb5c**

The data being passed into RenameUpload looks almost identical. The only differences I can spot are:

1. The tmp_name of the POST request always starts with 'php' and the PATCH with 'zfc' (can't see how that would make a difference, but at this point I am not taking any chances)

2. When calling PATCH, an actual file is created in the tmp directory (then fails). When POST is used, there isn't any file in the tmp directory (and ironically no issues). This happens by just uploading a file as well, before RenameUpload is called.

I searched a lot and found may similar issues. Most were really old and didn't offer any solutions. I also used multiple REST clients just to rule that out. File permissions look good as well (at least for the PATCH scenario). I am all out of ideas.

**Comment by Wilt** [comment]
There is a special `RenameUpload` class shipped with the Content-Negotiation module. This class can be found here:

https://github.com/zfcampus/zf-content-negotiation/blob/master/src/Filter/RenameUpload.php

 Is that the one you are talking about?

**Comment by sariabod** [comment]
@Wilt thanks for this. I didn't even think to look for a specific zfcampus filter. I changed from the zend version to zfcampus version and tried again. A couple things:

1. The call is being routed right back to parent::moveUploadedFile (line 49) anyway. The $request variable is null at that point.

2. As a test of my own curiosity, I forced it to not call parent::moveUploadedFile but ended with exact same error.

It has to be something I am not setting up correctly.

**Comment by sariabod** [comment]
@Wilt Ok, I think I got it working. The fact the request was null was bugging me. lt looks like I was simply missing this on the RenameUpload object.
```
setRequest(new Request());
```
After this it worked it like a charm. Thanks for the help!
