### ISSUE TITLE
Uni-directional ManyToOne/OneToOne repeated in Entity to same Target throws fatal DBAL exception

### ISSUE THREAD

**Issue by rkeet** [zfcampus/zf-apigility#201]
- [x] I was not able to find an [open](https://github.com/zfcampus/zf-apigility/issues?q=is%3Aopen) or [closed](https://github.com/zfcampus/zf-apigility/issues?q=is%3Aclosed) issue matching what I'm seeing.

I hope this is the place to open this issue instead of in Doctrine. Not sure though, please advise.

### Code to reproduce the issue

- Use Doctrine

- Have 2 Entity objects: Company & Location 
- Multiple associations exist from Company to Location, but 1 per property (see code)
- Associations are uni-directional
- One of associations is required (`nullable=false`), else they're the same but for the name

#### Additional config (probably not relevant)

- `zf-hal > metadata_map > Company::class > max_depth = 3` -> added
- `doctrine-hydrator > CompanyHydrator > strategies > locations = CollectionLink::class` -> added
- `zf-content-validation > Company\\Controller > input_filter = CompanyFieldsetInputFilter::class` -> modified
- `zf-input-filter` -> removed (replaced by class in `zf-content-validation`)

```php
class Company

/**
 * @var Location
 * @ORM\ManyToOne(targetEntity="Location", cascade={"persist", "remove"})
 *  // Or -> \OneToOne(targetEntity="Location", cascade={"persist", "remove"})
 * @ORM\JoinColumn(name="main_location_id", referencedColumnName="id", nullable=false)
 */
protected $mainLocation;

/**
 * @var Location
 * @ORM\ManyToOne(targetEntity="Location", cascade={"persist", "remove"})
 *  // Or -> \OneToOne(targetEntity="Location", cascade={"persist", "remove"})
 * @ORM\JoinColumn(name="billing_location_id", referencedColumnName="id", nullable=true)
 */
protected $billingLocation;
```

#### Demo POST data

```json
{
   "name":"New Farm",
   "mainLocation":{
   	"name": "The home",
   	"address": "All the way down the drive 33, 12345, FarmVille"
   },
   "billingLocation":{
   	"name": "The barn",
   	"address": "Beyond the house 22, 12345, FarmVille"
   }
}
```

### Expected results

I expected that I **must provide** the `mainLocation` property with a new `Location` object and _optionally_ do the same for `billingLocation`. 

### Actual results

With or without `billingLocation` (not required) in the test data above, but **with** the required `mainLocation`, the error below appears.

```json
{
    "trace": [
        {
            "file": "C:\\xampp\\htdocs\\api\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php",
            "line": 184,
            "function": "convertException",
            "class": "Doctrine\\DBAL\\Driver\\AbstractMySQLDriver",
            "type": "->",
            "args": [
                "An exception occurred while executing 'INSERT INTO companies (name, main_location_id, billing_location_id) VALUES (?, ?, ?)' with params [\"New Farm\", null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'main_location_id' cannot be null",
                {
                    "errorInfo": [
                        "23000",
                        1048,
                        "Column 'main_location_id' cannot be null"
                    ],
```

---

If I make `mainLocation` nullable (`nullable=true`) OR remove the other references to `Location`, this setup works. 

---

Now I've traced this into the UnitOfWork where I found that it tries to create the Company without first creating the Location object(s). As such, they "don't exist for real". They do in memory and they are persisted, just not flushed prior to Company, thus have no ID, inspecting the `$entity` variable confirms this.

---

Any help to point in a right direction or provide a solution would be greatly appreciated. I've been bashing this issue for 2 days straight now.

**Comment by weierophinney** [comment]
Please re-report this against [zf-apigility-doctrine](https://github.com/zfcampus/zf-apigility-doctrine/issues/new).

**Comment by rkeet** [comment]
Ok, done, thanks. Was wondering which repo would be most appropriate.
