### ISSUE TITLE
Not clear how to do backups / Backup command expected

### ISSUE THREAD

**Issue by modir** [zfcampus/zf-apigility#202]
At the moment it is not clear to me how to do backups of apigility. What I expect is either:

a) a button inside the admin interface which allows me to backup an API.

b) an article in the documentation how to do a backup with the existing tools

c) a command-line tool which would allow me to make a backup of the whole apigility instance.

I am not sure which of the three is the best solution. Hence I opened the issue here. Maybe it needs to be transferred to the [documentation](https://github.com/zfcampus/apigility-documentation) if b) would be the best solution.

**Comment by weierophinney** [comment]
Open-ended questions are best asked:

- In our [Slack](https://zendframework-slack.herokuapp.com)
- In our [forums](https://discourse.zendframework.com/c/questions/apigility)

The short answer: backups vary greatly between projects, based on project structure, database(s) used (if any), etc. For the code side, version control systems are your friend.
