### ISSUE TITLE
Joining Tables

### ISSUE THREAD

**Issue by lucasmonstrox** [zfcampus/zf-apigility#64]
You can join tables in apigility?

**Comment by zrecore** [comment]
Can we re-open this issue until we get a working example?

**Comment by jahkey** [comment]
Followed the steps in https://apigility.org/documentation/recipes/join-tables
However, after removing the configuration for zf-apigility.db-connected Users\V1\Rest\Users\UsersResource, I am getting the following error:

Unable to resolve service "user_locations" to a factory; are you certain you provided it during configuration?

Help please. Did we miss a step here? Thanks in advance!
