### ISSUE TITLE
Return image/jpeg with REST GET request

### ISSUE THREAD

**Issue by chadicus** [zfcampus/zf-apigility#80]
I have an API, i want to return a json response when a client requests an image such as
`/images/123`

This would return a json object containing metadata about the image. However if the client adds an extension I would like to return the image itself.
`/images/123.jpg`

This would return the image itself with a content-type of image/jpeg

Is this possible?

**Comment by rrubio** [comment]
Thank you for the help. I've tried the above, but still getting the  A 404 error occurred screen. I'd like to display images under the "public/img" folder on a mobile app, but so far i'm getting nowhere fast. I am new to Apigility so any help would assist me greatly and much appreciate it.

**Comment by mgoneau** [comment]
Thank you for this thread of information. I am trying to implement Accept: image/jpeg support and this put me on the right path.

I am having trouble finding information in google about creating the custom ImageModel and ImageStrategy but I'm thinking this must of been done a lot. I was wondering if you had any information of where I could find how to implement those correctly so I can use with Apigility Content Negotiation.

Thank you

**Comment by szoper** [comment]
I am trying to implement something similar for PDFs by myself, but looking at existing HalJsonModel and ancestor's I have no idea what methods my model should implement.

Is this tutorial relevant to Apigility?
https://samsonasik.wordpress.com/2012/12/10/zend-framework-2-step-by-step-create-custom-view-strategy/

**Comment by Wilt** [comment]
I actually made a `DownloadListener` for this. It will already return a Stream onDispatch. So in the end the application never gets as far as rendering a `ViewModel`. This turned out to be a much simpler solution.
