### ISSUE TITLE
OAuth redirect uri not working

### ISSUE THREAD

**Issue by davidtay** [zfcampus/zf-apigility#86]
If you use a subdirectory for your url like http://dev.mycompany.com/api/oauth/authorize?response_type=code&client_id=testclient&redirect_uri=/oauth/receivecode&state=xyz

the redirect goes to http://dev.mycompany.com/oauth/receivecode?code=900166a035c39dfac37e3cf98d37d3b4aa377de0&state=xyz

which 404s. 

Where do i find this line of code so I can fix it before the fix is pushed?

**Comment by alphen87** [comment]
I had this issue too, please make sure you runned composer install or update.
