### ISSUE TITLE
How to update via apigility

### ISSUE THREAD

**Issue by chateaux** [zfcampus/zf-apigility#87]
I have setup a basic api: /api/products

To query the collection I post to: /api/products
To query an individual item I post to: /api/products/1

I would like to learn how to update a product via the api and gather I need to be using a "put".

Further from this I am unsure what to do. Are there any examples I can look at to help me along?

thanks

**Comment by EMCP** [comment]
`POST` should never execute queries.. it's meant to create new data entities.  Please use `GET` instead.

Are you using a code connected or db connected service?

**Comment by chateaux** [comment]
Hi - I am using a code connected DB. I will use get in future.

What I am unclear on is really how to set up the api so that I have full access to all the methods in the resource.

Thanks

**Comment by EMCP** [comment]
I use POSTMAN client from Google Chrome in order to use the more exotic HTTP Verbs. ie ( `PUT` `DELETE` `PATCH` ..

How are you executing your HTTP calls?  If you follow the tutorial and initialize a code connected resource it should support many of those from the start.

to double check those verbs are enabled, look at your config file.

`modulename/config/module.config.php`

Notice you need to add in which HTTP Verbs are allowed for Collections AND entities...

```
  'zf-rest' => array(
        'Services\\V1\\Rest\\Services\\Controller' => array(
            'listener' => 'Services\\V1\\Rest\\Services\\ServicesResource',
            'route_name' => 'services.rest.services',
            'route_identifier_name' => 'services_id',
            'collection_name' => 'services_collection',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PATCH'
            ),
            'collection_query_whitelist' => array(
                0 => 'user_id',
                1 => 'provider',
                2 => 'type',
                3 => 'date_range',
                4 => 'sort_by',
                5 => 'sort_order'
            ),
            'page_size' => 250,
            'page_size_param' => null,
            'entity_class' => 'Services\\V1\\Rest\\Services\\ServicesEntity',
            'collection_class' => 'Services\\V1\\Rest\\Services\\ServicesCollection',
            'service_name' => 'Services',
        ),
```

**Comment by chateaux** [comment]
Ok yes, I have it setup correctly and I use PostMan too.

So my URL is: https://mysite.com/api/cart

I want to for instance update a pre-existing product so I assume I need to put to the URL, something like this:

put http://www.mysite.com/api/cart?prod_id=1&quantity=2&update_method=1&tax=0.00

When I do the above it simply returns: '1'



'Api\\V1\\Rest\\Cart\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\Cart\\CartResource',
            'route_name' => 'api.rest.cart',
            'route_identifier_name' => 'cart_id',
            'collection_name' => 'cart',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'prod_id',
                1 => 'quantity',
                2 => 'cart_id',
                3 => 'tax',
                4 => 'update_type',
            ),
            'page_size' => 25,
            'page_size_param' => 'page_items',
            'entity_class' => 'Api\\V1\\Rest\\Cart\\CartEntity',
            'collection_class' => 'Api\\V1\\Rest\\Cart\\CartCollection',
            'service_name' => 'cart',
        ),

**Comment by chateaux** [comment]
I see the problem, I have not included PUT under collections.
