### ISSUE TITLE
Simple apigility build with zf-deploy yields ZF errors

### ISSUE THREAD

**Issue by PipStyles** [zfcampus/zf-apigility#91]
Solved it with copying content of config/autoload/local.php into the global.php file in that same folder. My fault for not completely understanding the note in the Zf Deploy guidance.
This may at least help others who stumble at that step: You need to have the db (and other) config arrays present in global.php (not just local.php) when you run zfdeploy.php, otherwise the deployed Zf2 application will fail with the error below.
The guidance could be a bit clearer on this point.

(The other note, about changing the landing page route, is optional, but recommended if you're publishing and api for others to use!)

- - - - - - - - - 
Completely fresh apigility install (curl install method, first one listed in instructions).
Running local WAMP setup (PHP 5.5.12, Apache 2.4.9).
Made a few DB-connected REST services.
Local Postman requests to my_dev_folder/apigility/public/name _of_rest_service yielding collection results perfectly. So far so good - Apigility working as intended.
Build (using php vendor/zfcampus/zf-deploy/bin/zfdeploy.php build api.zip) appears to work fine. Zip file is built.
Unzip into build folder (/www).
Now, Local Postman requests to /www/api/public/name_of_rest_service yielding:

    Fatal error: Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotFoundException' with message 
    'ZF\Rest\Factory\RestControllerFactory::canCreateServiceWithName requires that a valid "listener" service be specified for controller my_app\V1\Rest\Themes\Controller; 
    no service found' in C:\<pathToServerRoot>\<appName>\www\api\vendor\zfcampus\zf-rest\src\Factory\RestControllerFactory.php on line 76

I think something is not getting across in the build process. I've examined the "Preparing to deploy" in https://apigility.org/documentation/deployment/intro but this seems to be something else. The fact that this is working quite happily in the "undeployed" version makes me think this is caused by something in the zf-deploy build process.

**Comment by AsterXxX** [comment]
@PipStyles How did you solved the problem?

**Comment by fivelas** [comment]
AsterXxX, he solved by doing what he says in his response. Read first period, please.
I had the same problem and just did what he says and it's now working for me.
