### ISSUE TITLE
SOAP server

### ISSUE THREAD

**Issue by Michal-sk** [zfcampus/zf-apigility#97]
I have searched and search trough far lands of the interwebs but did not find an answere. Do we have support for creating a SOAP server with apigility?

**Comment by jguittard** [comment]
IMO, it would have to be defined through a RPC service, in which you would inject your SOAP server instance.
Custom response rendering for SOAP envelopes would have to be defined too.

So, as for the answer, no, Apigility is meant to build and support REST services. But its structure allows you to implement SOAP endpoints.

**Comment by weierophinney** [comment]
Zend Framework provides a SOAP server implementation via the zend-soap component (https://github.com/zendframework/zend-soap with documentation at http://framework.zend.com/manual/current/en/modules/zend.soap.server.html). This could be implemented in a standalone script, or wrapped inside a controller easily (in Apigility, it would be an RPC controller with GET actions returning the WSDL and POST actions delegating to the server). That is the extent of our support for SOAP; we have no plans to provide ways to configure a SOAP server via Apigility.
