### ISSUE TITLE
Tags not updated

### ISSUE THREAD

**Issue by kenkataiwa** [zfcampus/zf-apigility#98]
I've recently updated dependencies via composer and while zf-apigility dependencies checked out v1.1.0 zf-apigility remained at v1.0.3 and this lead to a number of errors, (I'm not sure they relate but might be the reason).
So here is the versioning in the Apigility website, https://apigility.org/download :
![apigility - 1](https://cloud.githubusercontent.com/assets/2436107/7198288/72168e2a-e4f3-11e4-819e-f2d286c5bed0.PNG)

And here are the zf-apigility tags released so far: 
![apigilty - 2](https://cloud.githubusercontent.com/assets/2436107/7198293/7c96c61c-e4f3-11e4-941e-aa910beee4f3.PNG)

PS: I didn't know where else to report this, so figured "an issue" is as good as place as any, you can close it.

**Comment by weierophinney** [comment]
The official version for Apigility is not in the zf-apigility module, but in the zf-apigility-skeleton, as that's the only packaged version of Apigility we ship. The version of the zf-apigility module *is* currently 1.0.3, while  zf-apigility-skeleton is currently at 1.1.1.
